module.exports = {
	"LOGO_WIDTH_IN_STRIPE": 304,
	"RADIUS": 76,
	"CANVAS_WIDTH": 2800,
	"HEIGHT_START": 40,
	"HEIGHT_FINISH": 400,
	"LOGOS_COUNT": 43,
	"INITIAL_PADDING": 5,
	"PADDING_INCREMENT": 2
};
